### ISSUE TITLE
Missing custom.py files in environments

### ISSUE THREAD

**Issue by jakemsnyder** [datarobot/datarobot-user-models#57]
The Python environments refer to a custom.py file in the readme, but there is no custom.py file (so the link gives a 404 error). If the environments no longer use custom.py, can we update the readme to remove them?

https://github.com/datarobot/datarobot-user-models/blob/master/public_dropin_environments/python3_sklearn/README.md

**Comment by GlobalMin** [comment]
I'm reading the reference to custom.py here as potentially optional for inference models and necessary for training models, but in both cases should go in the custom model templates folder. The link to custom.py is in fact broken I think so that should be fixed but conceptually the description in the readme makes sense to me and is correct. Do you think it's misleading still? Perhaps a diagram with both the environment and the modeling files together that highlights the files needed in each for a standard set up and for larger changes would help.

@4dahalibut might be the right person to make this call.
